### ISSUE TITLE
404 SyntaxError when trying to view stream

### ISSUE THREAD

**Issue by FickleLife** [nats-nui/nui#62]
When I try open an empty or populated stream in NATS via NUI, I get `http:error:404 SyntaxError: The string did not match the expected pattern.` as seen below in the screenshot.

Any ideas what is going wrong? Seems like a very weird error, especially if there's nothing in the stream. I can successfully write messages to the stream, just not read them.  

Repoduction steps:

1.  Docker compose is below
2. Click on an empty or populated stream 

![Image](https://github.com/user-attachments/assets/ca78485f-ac3e-4824-9c64-f4b0455a6348)

```
version: '3.9'

services:
  nats:
    container_name: nats
    image: docker.io/nats:2.11.1
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
    ports:
      - "4222:4222"
      - "8222:8222"      
    volumes:
      - nats-data:/data
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
      - "--auth=${NATS_TOKEN}"
    
# creates page and product streams
  stream-setup: 
    container_name: stream-setup
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
      - NATS_SERVER=nats://nats:4222
    depends_on:
      - nats
       
    restart: on-failure:3

  nui:
    container_name: nui
    image: ghcr.io/nats-nui/nui:edge
    volumes:
      - ./db:/db
    ports:
      - "31312:31311" 
    depends_on:
      - nats

volumes:
  nats-data:
```
