### ISSUE TITLE
Nats context import with NKEY

### ISSUE THREAD

**Issue by boris-senapt** [nats-nui/nui#63]
I am running NUI in K8s, and I have added config to autoload contexts 

```yaml
autoloadContexts: true
contextsVolume:
  name: nui-contexts
  items:
    - key: a.json
      path: a.json
    - key: b.json
      path: b.json
```

(it seems unnecessary to require `items` to be set - it could just mount everything by default)

I create my secret - I'm using Tilt - with something like 

```python
k8s_yaml(secret_from_dict(
  name = "nui-contexts",
  namespace=NATS_NS,
  inputs = {
    'a.json' : """
    {
      "name": "a",
      "url": "nats-headless.nats.svc.cluster.local:4222",
      "nkey": "foo"
    }
    """,
    'b.json' : """
    {
      "name": "b",
      "url": "nats-headless.nats.svc.cluster.local:4222",
      "nkey": "bar"
    }
    """
}))
```

This works, and NUI imports the context. However - until I go into the UI and manually add the public part of each NKEY the UI will not connect to NATS.

Looking at `pkg/clicontext/clicontext.go` I see no way to set the public key, it's not read or updated in `internal/nui/connections_import.go`.
