### ISSUE TITLE
http:error:404 SyntaxError: Unexpected token 'C', "Cannot GET"... is not valid JSON

### ISSUE THREAD

**Issue by fruiting** [nats-nui/nui#64]
Hello!

I'm trying to read data from stream. In my code is everything is ok but in nui I've got problems. When I open stream messages I've got an error 
http:error:404
SyntaxError: Unexpected token 'C', "Cannot GET"... is not valid JSON

That error occurs even if I'm trying to read from an empty stream. When I'm trying to send data it's json like
```
{
    "msg": "hi"
}
```

What am I doing wrong?

<img width="1252" alt="Image" src="https://github.com/user-attachments/assets/a5919c8d-6515-4d15-a4dd-d1882d5ee71f" />

My docker-compose

```
nats:
    image: nats:2.11.1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: >
      -js
      --sd /nats/data
    volumes:
      - ./nats/data:/nats/data

nats-ui:
    image: ghcr.io/nats-nui/nui:latest
    ports:
      - "31311:31311"
    volumes:
      - ./nats/ui_db:/db
```
